### ISSUE TITLE
Rack hijack not available(Tubesock)

### ISSUE THREAD

**Issue by lephyrius** [torquebox/torquebox#195]
Im using Tubesock for creating websocket connections. 
Under Torquebox 4.0.alpha1 I get the error: Tubesock::HijackNotAvailable - Tubesock::HijackNotAvailable:

**Comment by bbrowning** [comment]
Enough of the Rack Hijack API is implemented to get Tubesock working. We'll do a 4.0.0.alpha2 release soon with this change.
