### ISSUE TITLE
TorqueBox 4 missing long running daemons

### ISSUE THREAD

**Issue by bbrowning** [torquebox/torquebox#199]
TorqueBox 3 had long-running daemons (confusingly called services) and we've had a few users ask to bring this feature back in TorqueBox 4. Immutant 2 already has them (https://github.com/immutant/immutant/blob/thedeuce/core/src/immutant/daemons.clj#L24) so the necessary bits already exist in WunderBoss.

**Comment by occamsRZR** [comment]
+1

**Comment by thoughtchad** [comment]
+1 only thing missing for me to upgrade without major rework

**Comment by tobias** [comment]
I've implemented supervised, optionally-singleton (inside WildFly) daemons. They are available in incremental build 370 (or newer): http://torquebox.org/4x/builds/

Currently, there are no formal docs other than the API docs: http://torquebox.org/4x/builds/370/docs/TorqueBox/Daemon.html#action-instance_method and the examples in the tests: https://github.com/torquebox/torquebox/blob/master/core/spec/daemon_spec.rb

If folks are willing to give this a try and let me know if it works for them, that would be swell.

**Comment by micred** [comment]
@tobias any hint to how use Deamon to handle the delayed_job worker? (or active job)?

**Comment by tobias** [comment]
@micred - If they provide some way to launch the worker from within a thread, then it should be straightforward. I've never used either (I haven't done any ruby in a long time), so I don't have more concrete advice, sorry.
