### ISSUE TITLE
Building self-contained Jar with Jar dependencies

### ISSUE THREAD

**Issue by swistaczek** [torquebox/torquebox#200]
Hi,
It would be great if TorqueBox (>= 4.) could support bundling Jar dependencies while bootstraing self-contained Jar. 

There is an emerging library for doing all Jar related dependency in jRuby enviroment called https://github.com/mkristian/jbundler by @mkristian that could be integrated just after (or 'instead of') rubygems bundling process.

**Comment by swistaczek** [comment]
@tobias if is it possible I would be glad to work on this issue. I have some troubles with setting up development enviroment for Torquebox. What time are development team usualy available on the IRC channel?

**Comment by bbrowning** [comment]
@swistaczek The development time is mostly in the US Eastern timezone and there's usually someone available anytime during that daytime.

Regarding jbundler, are you requesting that as part of generating an executable jar we run jbundler to pull in jar dependences if we detect the JRuby application uses it? Or are you requesting that TorqueBox itself use jbundler as part of our build?

**Comment by swistaczek** [comment]
Hey, thanks for reply!

I would like to make this two things described by you. In my opinion one result the second improvement. Currently self contained JAR bundling process forces several JARS into bundle, this may result in problems (jar hell) while you will try to bundle any jars that uses other version of dependencies (for example log4j exposing deprecated API). Usage of tool like jBundler may help in proper dependencies resolving that will help developers to automate resolving dependencies by hand.

As use case imagine that I would like to create self contained JAR for project that uses jbundler to setup [kafka client](https://github.com/joekiller/jruby-kafka).

@mkristian did great work and currently jBundler is able to resolve Mavenfile.
