### ISSUE TITLE
RuntimeError when failing to connect to Remote HornetQ server

### ISSUE THREAD

**Issue by kwando** [torquebox/torquebox#201]
`Java::JavaxJms::JMSRuntimeException: Failed to create session factory`
Is raised when a client cannot connect to a remote HornetQ  instance.

Maybe this should be wrapped into something more TB-ish?

**Comment by tobias** [comment]
What would something more TB-ish look like? A ruby exception wrapping the Java one?

**Comment by kwando** [comment]
I'm thinking some exception that is a subclass of ```TorqueBox::Error```. I do not really want to rescue Java exceptions in my code.
