### ISSUE TITLE
Torquebox 3.1.1 download link redirect to 404

### ISSUE THREAD

**Issue by swistaczek** [torquebox/torquebox#202]
Following link http://torquebox.org/release/org/torquebox/torquebox-dist/3.1.1/torquebox-dist-3.1.1-bin.zip will redirect you to not existing page (404).

**Comment by bbrowning** [comment]
For now I've taken the CDN out of the loop which has downloads working again. Now to figure out what's up with the CDN.

**Comment by bbrowning** [comment]
Closing this since downloads have been working for a few weeks.
