### ISSUE TITLE
[Torquebox4] error deploying plain rails 4.2 war to wildfly 

### ISSUE THREAD

**Issue by zigolab** [torquebox/torquebox#203]
I'm testing TorqueBox 4.0.0.alpha1 with a plain rails 4.2 app.
running:
> rails new testwar
> cd testwar
> bundle install
> torquebox war --destination wildfly-8.1.0.Final/standalone/deployments -v

I get the following error in wildly
> service jboss.undertow.deployment.default-server.default-host./testwar: Failed to start service
> ...
> Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.jruby.exceptions.RaiseException: (LoadError) load error: nokogiri/nokogiri -- java.lang.NoClassDefFoundError: com/sun/org/apache/xpath/internal/VariableStack

Since the problem seemed to be missing jars for nokogiri, I added serializer.jar, xalan.jar, xercesImpl.jar and xml-apis.jar to  ~/.rvm/rubies/jruby-1.7.18/lib, but I keep getting the same error.

Diving into the war, I noticed that in WEB-INF/lib/testwar.jar, I found the above files in the jars folder, but the file MET-INF/app.properties seems to ignore them:
> classpath=${extract_root}/jars/wunderboss-ruby-1.x.incremental.174.jar:${extract_root}/jars/wunderboss-rack.jar:${extract_root}/jars/jruby.jar

Is there a way to explicitly add to the classpath the missing files?

My setup is:
> OSX 10.10.1
> Java SE (build 1.8.0_25-b17) - Java HotSpot 64-Bit Server VM (build 25.25-b02, mixed mode)
> rvm 1.26.7
> jruby-1.7.18
> wildfly 8.1.0.Final

**Comment by bbrowning** [comment]
This is an issue that's already fixed in source but not in a TB4 release yet. Recent versions of Nokogiri depend upon some internal JDK classes that they shouldn't expect to be there. We've got a few other issues also fixed so perhaps it's time to put out a TB 4 alpha2 release soon.

**Comment by zigolab** [comment]
I have found another problem... same command but different environment.
Under Windows 7, when I run
> torquebox war --destination wildfly-8.1.0.Final/standalone/deployments -v

I get the following error
> Could not find thread_safe-0.3.4-java.gem for installation

This is the output of `gem list`
> thread_safe (0.3.4 java)

My setup is:
> Windows 7 SP1
> Java SE (build 1.7.0_60-b19) - Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)
> jruby 1.7.15 (1.9.3p392)
> wildfly-8.2.0.Final

**Comment by bbrowning** [comment]
Is there any additional information from Bundler when it complains about not being able to find the thread_safe gem? Does it always fail, or only sometimes? This looks like Bundler was unable to locate thread_safe in any of your configured gem sources (just rubygems.org?). Perhaps there was a temporary network issue, or perhaps something else involved. But, Bundler doesn't actually consult your locally installed gem list when searching for a gem and its dependencies.

**Comment by zigolab** [comment]
The fail happens only on Windows... On OS X, the same project  with the same configuration and dependencies has no problem...
The problems seems related to the way torquebox run bundler... 
If I run `bundle install`or `rails server` no error is thrown and `thread_safe (0.3.4 java)` results installed and linked...

**Comment by bbrowning** [comment]
The original problem is resolved in the 4.0.0.beta1 release. If you're still having issues with bundling gems, please open another issue.
