### ISSUE TITLE
Undertow request failed HttpServerExchange

### ISSUE THREAD

**Issue by gxbe** [torquebox/torquebox#205]
ERROR [io.undertow.request] (XNIO-1 task-26) Undertow request failed HttpServerExchange{ GET /sessions/loggedin}
org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `each' for "1":String

at WunderBoss::Rack::ResponseHandler.handle(/Users/deranged/Projects/jruby/lib/ruby/gems/shared/gems/torquebox-web-4.0.0.alpha1-java/lib/wunderboss_rack_response_handler.rb:35)

    class RackTest  
      def initialize(app)  
      end  
      def call(env)
        return [200, {"Content-Type" => "text/html"}, '1']
      end  
    end

**Comment by bbrowning** [comment]
The Rack spec dictates that the body can not be a string. At a minimum, it should be an array containing the single string ['1']. TorqueBox 3 was a bit slack in following the Rack spec, but we've tightened things up in TorqueBox 4.

"The Body itself should not be an instance of String, as this will
break in Ruby 1.9."
https://github.com/rack/rack/blob/master/SPEC

**Comment by gxbe** [comment]
oh fantastic!  I learned something new
