### ISSUE TITLE
New Torquebox 3.1.2 Release to pickup JRuby 1.7.19

### ISSUE THREAD

**Issue by tbeauvais** [torquebox/torquebox#209]
There is a bug fix in JRuby 1.7.19 that we are waiting on to upgrade to Rails 4.2. It looks like the pom.xml in Torquebox has already been updated to JRuby 1.7.19 so hopefully this just means pushing out a new release.

**Comment by bbrowning** [comment]
TorqueBox 3.1.2 is out w/ JRuby 1.7.19 - formal announcement will come shortly.
