### ISSUE TITLE
Plans for rake task support from packaged jar in 4.x?

### ISSUE THREAD

**Issue by nullstyle** [torquebox/torquebox#211]
Hey y'all,

Are there any plans to support the ability to run rake tasks from within a packaged torquebox 4 application?  Before I go down the path of duplicating what warbler does with `-S` (unpack the jar to a tmp dir, run tasks from there) I wanted to see if any of you have any better ideas.

Thanks!
-Scott

**Comment by bbrowning** [comment]
A few users have asked for this so it's something we definitely need to implement. We had a 'torquebox exec' in TorqueBox 3 and it just unpacked the jar to a tmp directory and ran from there. I think that's all we really can do.

**Comment by mjc** [comment]
Some way to run tasks inside WildFly/JBoss' existing JVM would definitely help those who use JNDI.
