### ISSUE TITLE
Option for Wunderboss unpacking directory?

### ISSUE THREAD

**Issue by jh125486** [torquebox/torquebox#212]
I'm deploying a torquebox4 app as a war file onto a Wildfly 8.2 server.
The problem I'm encountering is that the /tmp space on each of of Wildfly servers is capped at 512mb, and the torquebox app exploded is taking up 230mb in /tmp/wunderbossXXX. So two apps won't be able to run concurrently on the same server.  If the apps were unpacked into /tmp/wunderboss/XXXXX I could at least do some linking around the filesystem to get them to a more spacious area.

Is there a configuration option I'm missing?  
Or is there a better (standard) way to deploy a torquebox4 app for production?

Thanks in advance!

**Comment by bbrowning** [comment]
We're using the JVM's temporary directory logic to determine where to unpack the files. You can change the location of the temp directories by setting the java.io.tmpdir system property. Add something like the following to $WILDFLY_HOME/bin/standalone.conf:

    JAVA_OPTS="$JAVA_OPTS -Djava.io.tmpdir=/path/to/foo"

Hope that helps!

**Comment by jh125486** [comment]
It worked, thanks!
Is a war file the proper way for production deployment in the first place?  That's how I used to deploy with glassfish, but those were primitive days ;)

**Comment by bbrowning** [comment]
A war file is fine for production deployment. However, a simple executable jar file or just running the application off disk are also just as valid for production deployment. It all depends on what you're most comfortable with.
