### ISSUE TITLE
Rails.root returns path with backslashes on Windows on upgrade to 3.1.2 from 3.1.1

### ISSUE THREAD

**Issue by JackWCollins** [torquebox/torquebox#214]
Torquebox 3.1.2 seems to have introduced a breaking change for Windows users. For some reason that I'm still not 100% sure about, `Rails.root` returns a path with backslashes instead of forward slashes. For example:

Torquebox 3.1.1 with JRuby 1.7.13 (2.0.0p195)
`Rails.root = <Pathname:C:/Users/jacollins/RubymineProjects/ViewPoint>`

Torquebox 3.1.2 with JRuby 1.7.19 (2.0.0p598)
`Rails.root = <Pathname:C:\Users\jacollins\RubymineProjects\ViewPoint>`

I was running Rails 4.1.1 both times, so I am thinking it was TorqueBox that somehow caused this changed. I searched through the code and couldn't find a good reason why this happened. 

To fix this, I added this line to our `application.rb` file:
`config.root = Pathname.new(Rails.root.to_s.gsub(/\\/, '/'))`

That will return a path with forward slashes for Windows and Unix users. I'm happy to dig into this more if someone can help point me in the right direction.

**Comment by bbrowning** [comment]
My guess is this is actually coming from a change in the upgrade from JRuby 1.7.13 to 1.7.19 somewhere. To test, you could try running TorqueBox 3.1.1 with JRuby 1.7.19 or TorqueBox 3.1.2 with JRuby 1.7.13.

I took another look through all the commits between 3.1.1 and 3.1.2 and don't see anything else that could be causing this.

**Comment by JackWCollins** [comment]
Good idea - I'll take a look

**Comment by JackWCollins** [comment]
Indeed, this looks like a JRuby issue. I'll go ahead and close this and submit a JRuby issue.

### Working Versions

**Torquebox 3.1.2 with JRuby 1.7.13 (2.0.0-p195)**

    About your application's environment
    Ruby version              2.0.0-p195 (java)
    RubyGems version          2.1.9
    Rails version             4.1.1

    Rails.root = <Pathname:C:/Users/jacollins/RubymineProjects/ViewPoint>

**Torquebox 3.1.2 JRuby 1.7.13 (1.9.3-p392)**

    About your application's environment
    Ruby version              1.9.3-p392 (java)
    RubyGems version          2.1.9
    Rack version              1.5

    Rails.root = <Pathname:C:/Users/jacollins/RubymineProjects/ViewPoint>

### Broken Versions

**Torquebox 3.1.2 JRuby 1.7.19 (2.0.0p598)**

    About your application's environment
    Ruby version              2.0.0-p598 (java)
    RubyGems version          2.1.9
    Rails version             4.1.1

    Rails.root = <Pathname:C:\Users\jacollins\RubymineProjects\ViewPoint>

**Torquebox 3.1.2 JRuby 1.7.19 (1.9.3p551)**

    About your application's environment
    Ruby version              1.9.3-p551 (java)
    RubyGems version          2.1.9
    Rails version             4.1.1

    Rails.root = <Pathname:C:\Users\jacollins\RubymineProjects\ViewPoint>
