### ISSUE TITLE
Better gem description in rubygems

### ISSUE THREAD

**Issue by balasankarc** [torquebox/torquebox#216]
Hi,
I am packaging torquebox-no-op gem for Debian as part of GitLab packaging. I'm having trouble describing the use of gem and couldn't get any decent description from rubygems (It just states "TorqueBox No-Op Gem" ). Can you please add a more sensible description to the gem file (and also post it as a reply to this issue so that I can use it now itself, without waiting for a new version). It would be very much appreciated.

Thanks

**Comment by bbrowning** [comment]
Here's a copy of the information I added to the gem description in 9223eda:

```
Emulate TorqueBox APIs outside of TorqueBox

This gem allows you to run some TorqueBox applications outside of
TorqueBox by emulating the APIs provided by TorqueBox. Its
primary goal is to enable simple testing of applications that use
TorqueBox APIs without having to test those applications inside
TorqueBox itself.
```
The gem would only ever be used by applications that make sure of TorqueBox APIs. I wasn't aware GitLab could run on JRuby, so I'm surprised it uses TorqueBox APIs.

**Comment by balasankarc** [comment]
GitLab uses devise-async which has torquebox-no-op as a build dep. It is a long dependency chain. :D
