### ISSUE TITLE
Jarred rails app with recent sprockets can't serve precompiled assets

### ISSUE THREAD

**Issue by samwgoldman** [torquebox/torquebox#217]
Sprockets, which powers Rails' asset pipeline, changed an important filename to be a dotfile in version 3.0. [See issue](https://github.com/rails/sprockets/issues/7).

The presence of this file convinces Rails to serve the precompiled asset, which has a content hash appended to the file name. Without this file, Rails tries to serve "stylesheets/application.css" and "javascripts/application.js" which 404s.

I believe the issue is with torquebox itself, adds the app files to the jar by traversing `Dir.glob("**/*")`, which excludes all dotfiles.

The workaround for now is to downgrade sprockets to 2.12.4, which still uses the non-dotfile manifest.json file.

**Comment by bbrowning** [comment]
We purposely exclude dotfiles so we don't end up with things like the .git directory inside the jar. But, in this case, we either need to re-evaluate that decision or add an explicit check for the new sprocket's manifest. Thanks for the bug report!

**Comment by bbrowning** [comment]
For now I've committed a fix that explicitly includes Sprocket 3 manifest files. If we run into other cases of dotfiles needing to be included, we can revisit including all dotfiles.
