### ISSUE TITLE
Setting port with rackup fails 

### ISSUE THREAD

**Issue by blerins** [torquebox/torquebox#218]
Using `torquebox-web (= 4.0.0.beta1)`

    $ bundle exec rackup -s torquebox
    [...]
    11:59:08.101 INFO  [org.projectodd.wunderboss.web.Web] (main) Registered web context /
    11:59:08.107 INFO  [TorqueBox::Web::Server] (main) Starting TorqueBox::Web::Server 'default'
    11:59:08.661 INFO  [TorqueBox::Web::Server] (main) Listening for HTTP requests on localhost:9292

    $ bundle exec rackup -p 8080 -s torquebox
    [...]
    TypeError: cannot convert instance of class org.jruby.RubyString to int
        builder at /home/bruno/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/torquebox-web-4.0.0.beta1-java/lib/torquebox/web/server.rb:325
     initialize at /home/bruno/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/torquebox-web-4.0.0.beta1-java/lib/torquebox/web/server.rb:281
         server at /home/bruno/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/torquebox-web-4.0.0.beta1-java/lib/torquebox/web/server.rb:121
            run at /home/bruno/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/torquebox-web-4.0.0.beta1-java/lib/torquebox/web/server.rb:106
            run at /home/bruno/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/torquebox-web-4.0.0.beta1-java/lib/rack/handler/torquebox.rb:38
          start at /home/bruno/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/rack-1.6.1/lib/rack/server.rb:286
          start at /home/bruno/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/rack-1.6.1/lib/rack/server.rb:147
         (root) at /home/bruno/.rbenv/versions/jruby-1.7.11/lib/ruby/gems/shared/gems/rack-1.6.1/bin/rackup:4
           load at org/jruby/RubyKernel.java:1101
         (root) at /home/bruno/.rbenv/versions/jruby-1.7.11/bin/rackup:23

**Comment by bbrowning** [comment]
Thanks for the bug report! This is fixed for the next release.

**Comment by blerins** [comment]
Cool :)
