### ISSUE TITLE
Environment always resetting to development in jars

### ISSUE THREAD

**Issue by bbrowning** [torquebox/torquebox#219]
No matter how an executable jar/war is created, the environment is always getting reset to development. It looks like https://github.com/torquebox/torquebox/blob/master/web/lib/torquebox/web/cli.rb#L30 is probably the culprit.

**Comment by y8** [comment]
Just in case, as @bbrowning said on irc: workaround is to pass `-e <environment_name>`. 

Like: ` java -jar foo.jar -e production`
