### ISSUE TITLE
Graceful shutdown

### ISSUE THREAD

**Issue by mohamedhafez** [torquebox/torquebox#231]
Is there a way to gracefully shut down a process started with `torquebox run`? (completing existing requests but rejecting new ones, then shutting down). If so, could it be put into the documentation?

**Comment by bbrowning** [comment]
We do attempt to shut things down gracefully if you CTRL+C or send a SIGINT to the torquebox process. I actually don't know if this waits for in-flight requests to complete or terminates them abruptly. It would be worth a test to see how it behaves.

**Comment by mohamedhafez** [comment]
They are definitely terminated abruptly, I tried SIGINT and SIGTERM before posting this issue and in-flight requests were dropped.

**Comment by mohamedhafez** [comment]
Finishing in flight requests while rejecting new ones with a 502 or 503 would be great because it would allow [zero downtime deploys via nginx](http://blog.argteam.com/coding/hardening-node-js-for-production-part-3-zero-downtime-deployments-with-nginx/).
