### ISSUE TITLE
Torquebox 3.1.2 - Load error on VariableStack Java class

### ISSUE THREAD

**Issue by ianderse** [torquebox/torquebox#233]
I am getting a load error on startup using torquebox 3.1.2: missing class name (`com.sun.org.apache.xpath.internal.VariableStack')

Opening the torquebox console and trying to load that class leads to the following:
```
>> com.sun.org.apache.xpath.internal.VariableStack
=> Error: missing class name (`com.sun.org.apache.xpath.internal.VariableStack')
```

However, if I downcase VariableStack the class loads:
```
>> com.sun.org.apache.xpath.internal.variablestack
=> Java::ComSunOrgApacheXpathInternalVariablestack
```

The same first command in jirb works fine in the same environment:
```
irb(main):001:0> com.sun.org.apache.xpath.internal.VariableStack
=> Java::ComSunOrgApacheXpathInternal::VariableStack
```

**Comment by ianderse** [comment]
Looks like https://github.com/torquebox/torquebox/issues/203 addresses this issue as well. Any chance of the fix mentioned by @bbrowning being backported to 3.1.2?

**Comment by bbrowning** [comment]
This has been fixed in TorqueBox 3 and will be in the upcoming 3.2.0 release.
