### ISSUE TITLE
[Torquebox 4] Empty 304 Response gets Transfer-Encoding Header added (or: Wunderboss Upgrade)

### ISSUE THREAD

**Issue by helle** [torquebox/torquebox#236]
torquebox-web seems to have the same issue a wildfly user described here: https://github.com/wildfly/wildfly/issues/8560

The solution seems to be to upgrade undertow to a current version. I added a spec and verified the upgrade solves the issue here:

https://github.com/helle/torquebox/tree/wunderboss_upgrade

Unfortunately one of the caching specs fails after the upgrade and I don't anything about that part. So no pull request for now. We are going to run the upgraded torquebox-web in our staging environment for a few days to see if there are any other unforeseen problems.

**Comment by bbrowning** [comment]
Newer wunderboss versions have some much bigger web-related changes that are keeping me from upgrading to the latest wunderboss just yet. However, we do have a maintenance branch of wunderboss that TorqueBox 4 uses and I'll look into upgrading undertow there.

**Comment by bbrowning** [comment]
I've upgraded WunderBoss on master and also added your test case from that branch to our suite. Thanks for the test and figuring out the fix!
