### ISSUE TITLE
[Torquebox 4] threading issue when not serving precompiled assets

### ISSUE THREAD

**Issue by jaydanielian** [torquebox/torquebox#240]
Trying to run our rails app on ruby 9K and torquebox 4, we run into a strange threading problem that would cause the server to not respond to requests. I was able to get around this by doing a bundle exec rake assets:precompile  before starting torquebox server. However, if I didn't do that, and it tried to precompile on the fly - it would very frequently error out with this message, and the server would not response to requests (that included assets in the rails pipeline, so that is to say 99% of requests :) 

error trace:
ActionView::Template::Error (can not use Context instance already associated with some thread):
<html>
<head>
 <%= stylesheet_link_tag    'application', media: 'all' %>
    6:   <%= stylesheet_link_tag    'entity_states', media: 'all' %>
    7: 
    8:   <%= javascript_include_tag "application" %>
  org.mozilla.javascript.Context.enter(org/mozilla/javascript/Context.java:411)
  org.mozilla.javascript.ContextFactory.enterContext(org/mozilla/javascript/ContextFactory.java:586)
  java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
  RUBY.do_open(therubyrhino (2.0.4) lib/rhino/context.rb:265)
  RUBY.open(therubyrhino (2.0.4) lib/rhino/context.rb:252)
  RUBY.eval(therubyrhino (2.0.4) lib/rhino/context.rb:140)
  RUBY.eval(execjs (2.6.0) lib/execjs/ruby_rhino_runtime.rb:28)
  RUBY.exec(execjs (2.6.0) lib/execjs/ruby_rhino_runtime.rb:20)
  RUBY.run_uglifyjs(uglifier (2.7.0) lib/uglifier.rb:200)
  RUBY.compile(uglifier (2.7.0) lib/uglifier.rb:178)
  RUBY.call(sprockets (3.6.0) lib/sprockets/uglifier_compressor.rb:52)
  RUBY.call(sprockets (3.6.0) lib/sprockets/uglifier_compressor.rb:28)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.sprockets_minus_3_dot_6_dot_0.lib.sprockets.processor_utils.call_processor(sprockets (3.6.0) lib/sprockets/processor_utils.rb:75)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.sprockets_minus_3_dot_6_dot_0.lib.sprockets.processor_utils.block in call_processors(sprockets (3.6.0) lib/sprockets/processor_utils.rb:57)
  org.jruby.RubyArray.reverse_each(org/jruby/RubyArray.java:1643)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.sprockets_minus_3_dot_6_dot_0.lib.sprockets.processor_utils.call_processors(sprockets (3.6.0) lib/sprockets/processor_utils.rb:56)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.sprockets_minus_3_dot_6_dot_0.lib.sprockets.loader.load_from_unloaded(sprockets (3.6.0) lib/sprockets/loader.rb:134)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.sprockets_minus_3_dot_6_dot_0.lib.sprockets.loader.block in load(sprockets (3.6.0) lib/sprockets/loader.rb:60)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.sprockets_minus_3_dot_6_dot_0.lib.sprockets.loader.fetch_asset_from_dependency_cache(sprockets (3.6.0) lib/sprockets/loader.rb:317)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.sprockets_minus_3_dot_6_dot_0.lib.sprockets.loader.load(sprockets (3.6.0) lib/sprockets/loader.rb:44)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.sprockets_minus_3_dot_6_dot_0.lib.sprockets.cached_environment.block in initialize(sprockets (3.6.0) lib/sprockets/cached_environment.rb:20)
  org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
  org.jruby.RubyHash.default(org/jruby/RubyHash.java:716)
  org.jruby.RubyHash.[](org/jruby/RubyHash.java:1104)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.sprockets_minus_3_dot_6_dot_0.lib.sprockets.cached_environment.load(sprockets (3.6.0) lib/sprockets/cached_environment.rb:47)
  RUBY.find_asset(sprockets (3.6.0) lib/sprockets/base.rb:66)
  RUBY.find_all_linked_assets(sprockets (3.6.0) lib/sprockets/base.rb:73)
  RUBY.block in find(sprockets (3.6.0) lib/sprockets/manifest.rb:134)
  org.jruby.RubyArray.each(org/jruby/RubyArray.java:1560)
  RUBY.find(sprockets (3.6.0) lib/sprockets/manifest.rb:133)
  org.jruby.RubyEnumerator.each(org/jruby/RubyEnumerator.java:296)
  org.jruby.RubyEnumerable.map(org/jruby/RubyEnumerable.java:800)
  RUBY.precompiled_assets(sprockets-rails (3.0.4) lib/sprockets/railtie.rb:49)
  RUBY.asset_precompiled?(sprockets-rails (3.0.4) lib/sprockets/railtie.rb:34)
  RUBY.block in Railtie(sprockets-rails (3.0.4) lib/sprockets/railtie.rb:214)
  org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
  RUBY.precompiled?(sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:345)
  RUBY.raise_unless_precompiled_asset(sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:349)
  RUBY.digest_path(sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:323)
  RUBY.asset_path(sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:311)
  RUBY.block in resolve_asset_path(sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:89)
  RUBY.block in resolve_asset(sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:229)
  org.jruby.RubyEnumerable.detect(org/jruby/RubyEnumerable.java:606)
  RUBY.resolve_asset(sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:228)
  RUBY.resolve_asset_path(sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:88)
  RUBY.compute_asset_path(sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:78)
  RUBY.asset_path(actionview (4.2.6) lib/action_view/helpers/asset_url_helper.rb:135)
  RUBY.stylesheet_path(actionview (4.2.6) lib/action_view/helpers/asset_url_helper.rb:267)
  RUBY.block in stylesheet_link_tag(actionview (4.2.6) lib/action_view/helpers/asset_tag_helper.rb:97)
  org.jruby.RubyArray.map(org/jruby/RubyArray.java:2300)
  RUBY.stylesheet_link_tag(actionview (4.2.6) lib/action_view/helpers/asset_tag_helper.rb:96)
  RUBY.block in stylesheet_link_tag(sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:172)
  org.jruby.RubyArray.map(org/jruby/RubyArray.java:2300)
  RUBY.stylesheet_link_tag(sprockets-rails (3.0.4) lib/sprockets/rails/helper.rb:170)
  RUBY._app_views_layouts_application_html_erb___1424891343_11146(app/views/layouts/application.html.erb:5)
  RUBY.block in render(actionview (4.2.6) lib/action_view/template.rb:145)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.activesupport_minus_4_dot_2_dot_6.lib.active_support.notifications.instrument(activesupport (4.2.6) lib/active_support/notifications.rb:166)
  RUBY.instrument(actionview (4.2.6) lib/action_view/template.rb:333)
  RUBY.render(actionview (4.2.6) lib/action_view/template.rb:143)
  RUBY.render_with_layout(actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:66)
  RUBY.render_template(actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:52)
  RUBY.render(actionview (4.2.6) lib/action_view/renderer/template_renderer.rb:14)
  RUBY.render_template(actionview (4.2.6) lib/action_view/renderer/renderer.rb:46)
  RUBY.render(actionview (4.2.6) lib/action_view/renderer/renderer.rb:27)
  RUBY._render_template(actionview (4.2.6) lib/action_view/rendering.rb:100)
  RUBY._render_template(actionpack (4.2.6) lib/action_controller/metal/streaming.rb:217)
  RUBY.render_to_body(actionview (4.2.6) lib/action_view/rendering.rb:83)
  RUBY.render_to_body(actionpack (4.2.6) lib/action_controller/metal/rendering.rb:32)
  RUBY.render_to_body(actionpack (4.2.6) lib/action_controller/metal/renderers.rb:37)
  RUBY.render(actionpack (4.2.6) lib/abstract_controller/rendering.rb:25)
  RUBY.render(actionpack (4.2.6) lib/action_controller/metal/rendering.rb:16)
  RUBY.block in render(actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:44)
  RUBY.block in ms(activesupport (4.2.6) lib/active_support/core_ext/benchmark.rb:12)
  RUBY.realtime(/home/siq/.rvm/rubies/jruby-9.0.4.0/lib/ruby/stdlib/benchmark.rb:303)
  RUBY.ms(activesupport (4.2.6) lib/active_support/core_ext/benchmark.rb:12)
  RUBY.block in render(actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:44)
  RUBY.cleanup_view_runtime(actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:87)
  RUBY.cleanup_view_runtime(activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:25)
  RUBY.render(actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:43)
  RUBY.default_render(actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:10)
  RUBY.send_action(actionpack (4.2.6) lib/action_controller/metal/implicit_render.rb:5)
  RUBY.process_action(actionpack (4.2.6) lib/abstract_controller/base.rb:198)
  RUBY.process_action(actionpack (4.2.6) lib/action_controller/metal/rendering.rb:10)
  RUBY.block in process_action(actionpack (4.2.6) lib/abstract_controller/callbacks.rb:20)
  org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
  RUBY.call(activesupport (4.2.6) lib/active_support/callbacks.rb:117)
  RUBY.block in compile(activesupport (4.2.6) lib/active_support/callbacks.rb:555)
  org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
  RUBY.call(activesupport (4.2.6) lib/active_support/callbacks.rb:505)
  RUBY.__run_callbacks__(activesupport (4.2.6) lib/active_support/callbacks.rb:92)
  RUBY._run_process_action_callbacks(activesupport (4.2.6) lib/active_support/callbacks.rb:778)
  RUBY.run_callbacks(activesupport (4.2.6) lib/active_support/callbacks.rb:81)
  RUBY.process_action(actionpack (4.2.6) lib/abstract_controller/callbacks.rb:19)
  RUBY.process_action(actionpack (4.2.6) lib/action_controller/metal/rescue.rb:29)
  RUBY.block in process_action(actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:32)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.activesupport_minus_4_dot_2_dot_6.lib.active_support.notifications.block in instrument(activesupport (4.2.6) lib/active_support/notifications.rb:164)
  RUBY.instrument(activesupport (4.2.6) lib/active_support/notifications/instrumenter.rb:20)
  home.siq.siqweb4.shared.bundle.jruby.$2_dot_2_dot_0.gems.activesupport_minus_4_dot_2_dot_6.lib.active_support.notifications.instrument(activesupport (4.2.6) lib/active_support/notifications.rb:164)
  RUBY.process_action(actionpack (4.2.6) lib/action_controller/metal/instrumentation.rb:30)
  RUBY.process_action(actionpack (4.2.6) lib/action_controller/metal/params_wrapper.rb:250)
  RUBY.process_action(activerecord (4.2.6) lib/active_record/railties/controller_runtime.rb:18)
  RUBY.process(actionpack (4.2.6) lib/abstract_controller/base.rb:137)
  RUBY.process(actionview (4.2.6) lib/action_view/rendering.rb:30)
  RUBY.dispatch(actionpack (4.2.6) lib/action_controller/metal.rb:196)
  RUBY.dispatch(actionpack (4.2.6) lib/action_controller/metal/rack_delegation.rb:13)
  RUBY.block in action(actionpack (4.2.6) lib/action_controller/metal.rb:237)
  org.jruby.RubyProc.call(org/jruby/RubyProc.java:318)
  RUBY.dispatch(actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:74)
  RUBY.serve(actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:43)
  RUBY.serve(actionpack (4.2.6) lib/action_dispatch/routing/mapper.rb:49)
  RUBY.block in serve(actionpack (4.2.6) lib/action_dispatch/journey/router.rb:43)
  org.jruby.RubyArray.each(org/jruby/RubyArray.java:1560)
  RUBY.serve(actionpack (4.2.6) lib/action_dispatch/journey/router.rb:30)
  RUBY.call(actionpack (4.2.6) lib/action_dispatch/routing/route_set.rb:817)
  RUBY.call!(omniauth (1.2.2) lib/omniauth/strategy.rb:186)
  RUBY.call(omniauth (1.2.2) lib/omniauth/strategy.rb:164)
  RUBY.block in call(warden (1.2.3) lib/warden/manager.rb:35)
  org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1098)
  RUBY.call(warden (1.2.3) lib/warden/manager.rb:34)
  RUBY.call(rack (1.6.4) lib/rack/etag.rb:24)
  RUBY.call(rack (1.6.4) lib/rack/conditionalget.rb:25)
  RUBY.call(rack (1.6.4) lib/rack/head.rb:13)
  RUBY.call(actionpack (4.2.6) lib/action_dispatch/middleware/params_parser.rb:27)
  RUBY.call(actionpack (4.2.6) lib/action_dispatch/middleware/flash.rb:260)
  RUBY.context(rack (1.6.4) lib/rack/session/abstract/id.rb:225)
  RUBY.call(rack (1.6.4) lib/rack/session/abstract/id.rb:220)
  RUBY.call(actionpack (4.2.6) lib/action_dispatch/middleware/cookies.rb:560)
  RUBY.call(activerecord (4.2.6) lib/active_record/query_cache.rb:36)
  RUBY.call(activerecord (4.2.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:653)
  RUBY.block in call(actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:29)
  RUBY.__run_callbacks__(activesupport (4.2.6) lib/active_support/callbacks.rb:88)
  RUBY._run_call_callbacks(activesupport (4.2.6) lib/active_support/callbacks.rb:778)
  RUBY.run_callbacks(activesupport (4.2.6) lib/active_support/callbacks.rb:81)
  RUBY.call(actionpack (4.2.6) lib/action_dispatch/middleware/callbacks.rb:27)
  RUBY.call(actionpack (4.2.6) lib/action_dispatch/middleware/remote_ip.rb:78)
  RUBY.call(actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:17)
  RUBY.call(actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30)
  RUBY.call_app(railties (4.2.6) lib/rails/rack/logger.rb:38)
  RUBY.call(railties (4.2.6) lib/rails/rack/logger.rb:22)
  RUBY.call(actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21)
  RUBY.call(rack (1.6.4) lib/rack/methodoverride.rb:22)
  RUBY.call(rack (1.6.4) lib/rack/runtime.rb:18)
  RUBY.call(rack (1.6.4) lib/rack/sendfile.rb:113)
  RUBY.call(railties (4.2.6) lib/rails/engine.rb:518)
  RUBY.call(railties (4.2.6) lib/rails/application.rb:165)
  org.projectodd.wunderboss.rack.RackApplication.call(org/projectodd/wunderboss/rack/RackApplication.java:53)
  org.projectodd.wunderboss.rack.RackHandler.handleRequest(org/projectodd/wunderboss/rack/RackHandler.java:36)
  io.undertow.server.session.SessionAttachmentHandler.handleRequest(io/undertow/server/session/SessionAttachmentHandler.java:68)
  io.undertow.server.handlers.PredicateHandler.handleRequest(io/undertow/server/handlers/PredicateHandler.java:43)
  io.undertow.server.Connectors.executeRootHandler(io/undertow/server/Connectors.java:197)
  io.undertow.server.HttpServerExchange$1.run(io/undertow/server/HttpServerExchange.java:759)
  java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1145)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:615)
  java.lang.Thread.run(java/lang/Thread.java:745)

You can see once it tried to access the javascript assets in the view - it chokes out with some random thread context error.  Maybe this isn't a true error, or perhaps there are other reasons for this behavior. But I wanted to document it in case others noticed a similar issue.

**Comment by bbrowning** [comment]
At first glance this does look like a threading issue but one in therubyrhino or somewhere else in the asset compilation stack.
