### ISSUE TITLE
Default gems not working from inside fatjar

### ISSUE THREAD

**Issue by egomolka** [torquebox/torquebox#242]
I tried running this incremental build under JRuby 9.1.0.0. I successfully ran my web app on my workstation; however, when I deployed the web app to a server and then tried to perform a db migration with rake , I received an error, as seen here:

"18:22:30.397 INFO  [org.projectodd.wunderboss] (main) Initializing application as ruby
Could not find json-1.8.3-java in any of the sources
Run `bundle install` to install missing gems."

- My jar command: "jruby -S torquebox jar --bundle-without test development"

- My migrate command: "java -jar jar_file_name.jar jruby -S rake db:migrate"

The server has no JRuby environment. Everything is contained within the JAR file. I confirmed that json-1.8.3-java was contained within my sources.

I resolved the problem by switching back to JRuby 9.0.5.0

**Comment by t3hk0d3** [comment]
@egomolka Probably JAR handling were somehow changed in JRuby 9.1.0.0

**Comment by bbrowning** [comment]
I'm getting a similar issue in our integration tests when running under 9.1.1.0, although for the rake gem instead of the json gem. I'll add more notes once I figure out what's going on.

**Comment by anichenka** [comment]
just for stats:
torquebox 4.x.incremental.383, jruby 9.1.2.0 - still the same problem (for me it is json, not rake)

**Comment by bbrowning** [comment]
It looks like we're not properly packaging default gems, which were introduced in more recent RubyGems versions. This is why it only impacts json, rake, and a few others. I'm working on a fix for this now and updated the bug's title to reflect the underlying issue.

**Comment by bbrowning** [comment]
Incremental build 387 has this change if anyone wants to try and verify this issue is fixed.

**Comment by egomolka** [comment]
Thanks so much for resolving this!
I have just confirmed the fix using incremental build 387 under JRuby-9.1.2.0. Prior to the fix, I encountered a failure when I tried run a rake migration using my jar file, using the command:
"java -jar jar_file_name.jar jruby -S rake db:migrate"
Today, I successfully ran the rake migration, brought up my app, logged on to the app, and viewed some of my data.

**Comment by bbrowning** [comment]
Thanks for confirming the fix!
