### ISSUE TITLE
4.0.0.beta3 release ETA?

### ISSUE THREAD

**Issue by t3hk0d3** [torquebox/torquebox#243]
Currently we have to use git reference on master branch in Gemfile, and that is not best idea ever.

It would be awesome if you guys would release beta3.

We currently use master branch in production environment on >30k RPM and no a single serious issue.

**Comment by jcode** [comment]
+1

On Thu, May 19, 2016 at 1:59 PM, Igor Yamolov <notifications@github.com>
wrote:

> Currently we have to use git reference on master branch in Gemfile, and
> that is not best idea ever.
>
> It would be awesome if you guys would release beta3.
>
> We currently use master branch in production environment on >30k RPM and
> no a single serious issue.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/torquebox/torquebox/issues/243>
>



-- 
-- 
José Antonio Silva Portell
CTO
modyo.com

Av. Bicentenario 3883 Of. 303, Vitacura, Chile
phone: (56-2) 25871821 mobile: (56-9) 82179132
skype:  silva.portell

**Comment by bbrowning** [comment]
I'm working through some out of memory errors in the TB4 integration test suite right now that our Travis CI job found. It looks like something in the latest JRuby versions is using a lot more memory in some cases, but I haven't tracked down the cause yet.

**Comment by bbrowning** [comment]
4.0.0.beta3 is now out - a release announcement will come shortly. https://github.com/torquebox/torquebox/blob/v4.0.0.beta3/CHANGELOG.md
