### ISSUE TITLE
Errno::ENOENT: No such file or directory - C:/dev/null when executing jar command on windows

### ISSUE THREAD

**Issue by rob99** [torquebox/torquebox#247]
Torquebox 4 beta 3, JRuby 9.1.2.0

```
 C:\scripts\app>bundle exec torquebox jar
 19:09:10.670 INFO  Bundling gem dependencies
 Errno::ENOENT: No such file or directory - C:/dev/null
  initialize at org/jruby/RubyFile.java:360
        open at org/jruby/RubyIO.java:1129
       <top> at <script>:1
             at :1
             at :1
        load at org/jruby/RubyKernel.java:962
       <top> at C:\NotBackedUp\brownr12\downloads\jruby-9.1.2.0\bin\torquebox:22
```

I can see at https://github.com/torquebox/torquebox/blob/master/core/lib/torquebox/cli/jar.rb#L327 we check the `PLATFORM` constant for `mswin` however when using jruby this constant will always return `java`

I have hacked my gem to change this line to: 

```
dev_null = 'NUL'
```

... now I don't get any error but I don't get any jar.

**Comment by rob99** [comment]
I was able to move past the error by commenting the following lines out of `cli.rb`


       # unless %W(DEBUG TRACE).include?(TorqueBox::Logger.log_level)
          # dev_null = PLATFORM =~ /mswin/ ? 'NUL' : '/dev/null'
          # ruby.evalScriptlet("$stdout = File.open('#{dev_null}', 'w')")
        # end

**Comment by micred** [comment]
Same problem here. 
Have you made a fork?

The strange thing is that my Rails conf is `config.log_level = :debug` so it should not go inside that block.
Why do I have TorqueBox::Logger.log_level = INFO even if Rails log level is DEBUG?

**Comment by rob99** [comment]
No fork from me as yet.  I only know how to get around it for myself, not sure how not break it for others,.  Also not exactly sure what this is trying to do in the first place.

Note: your rails log level is different to you torquebox log level - they are different logs, by default.
