### ISSUE TITLE
no such file to load -- racc/cparse-jruby

### ISSUE THREAD

**Issue by rob99** [torquebox/torquebox#249]
Torquebox 4 beta 3, JRuby 9.1.2

```
C:\scripts\cml>java -jar myapp.jar -S rake routes
11:06:58.580 INFO  [org.projectodd.wunderboss] (main) Initializing application as ruby
no such file to load -- racc/cparse-jruby
org/jruby/RubyKernel.java:944:in `require'
<snip>
```

If we look at `lib\ruby\stdlib\racc\parser.rb` line 195 we see... 

```
  if Object.const_defined?(:RUBY_ENGINE) and RUBY_ENGINE == 'jruby'
    require 'racc/cparse-jruby.jar'
    com.headius.racc.Cparse.new.load(JRuby.runtime, false)
  else
    require 'racc/cparse'
  end
```

However when we look at `lib\ruby\gems\shared\gems\torquebox-core-4.0.0.beta3-java\lib\torquebox\cli\jar.rb` line 189 we see:

```
  def add_app_files(jar_builder, options)
    @logger.trace("Adding application files to jar...")
    exclude = [Regexp.new("^[^/]*\.(jar|war)")]
    if options[:exclude]
      exclude += options[:exclude].map { |e| Regexp.new("^#{e}") }
    end
    add_files(jar_builder,
              :file_prefix => Dir.pwd,
              :pattern => "/**/{*,\.*manifest*}",
              :jar_prefix => "app",
              :exclude => exclude)
  end
```

Which means that no `jar` or `war` file is bundled into the jar.

**Comment by rob99** [comment]
I found the problem is because when we enter `Torquebox::CLI::Jar#add_files` with options:

    {:file_prefix=>"C:/jruby-9.1.2.0/lib", :pattern=>"/**/*", :jar_prefix=>"jruby/lib", :exclude=>["jruby.jar", "ruby/gems/shared"]}

... the file `cparse-jruby.jar` is being excluded because the path includes the string `jruby.jar`.  Obviously this is an unintentional side-effect.

**Comment by rob99** [comment]
I was able to work around the problem by editing

[https://github.com/torquebox/torquebox/blob/master/core/lib/torquebox/cli/jar.rb#L160](url)

Change:

     :exclude => ["jruby.jar", "ruby/gems/shared"])


...to...

     :exclude => [/^jruby.jar/, "ruby/gems/shared"])

**Comment by micred** [comment]
same problem here

**Comment by micred** [comment]
I changed:

     :exclude => ["jruby.jar", "ruby/gems/shared"])

to:

    :exclude => ["ruby/gems/shared"])


I'm new to jRuby so I don't know the side effect of this change... apparently it works.
