### ISSUE TITLE
[Torquebox 3] Updating the Jruby version

### ISSUE THREAD

**Issue by sylverfyst** [torquebox/torquebox#265]
If I wanted to update Jruby on the server from 9.1.5.0 to the latest version, how would I go about doing it?

**Comment by mzaccari** [comment]
I just finished upgrading our torquebox staging environment to use 9.1.17.0, and haven't found any issues yet. Here's the change I made: https://github.com/torquebox/torquebox/pull/267

After running `mvn -s support/settings.xml install`, cd to `build/assembly/target/stage/` and the `torquebox` directory should have the build:

```bash
$ ls -la build/assembly/target/stage/torquebox/
drwxrwxr-x 5 michael michael 4096 May 17 15:41 .
drwxrwxr-x 5 michael michael 4096 May 17 16:01 ..
drwxrwxr-x 7 michael michael 4096 Mar 19  2014 jboss
drwxr-xr-x 6 michael michael 4096 Apr 20 13:27 jruby
-rw-rw-r-- 1 michael michael  126 May 17 15:41 Rakefile
drwxrwxr-x 5 michael michael 4096 May 17 15:41 share
```
