### ISSUE TITLE
Torquebox 4.0 GA Release Timeline

### ISSUE THREAD

**Issue by urenpatelce** [torquebox/torquebox#268]
Hi,
    Right now we are on Torquebox 3.2.0 and wanted to update on 4.0 but found that still beta is released. Any idea when a stable release is going to happen.

One more thing is we are trying to run Torquebox with 3.2.0 but getting below error. Any pointers or help would be appreciated.

Caused by: java.lang.NoClassDefFoundError: jdk/internal/reflect/ConstructorAccessorImpl

Thanks.

**Comment by TheKidCoder** [comment]
Bumping this - Is this project still maintained?

**Comment by bbrowning** [comment]
No - TorqueBox is not actively maintained.

**Comment by abhichvn** [comment]
@bbrowning We are also using Torquebox in production which gives us better scaling and stability with **JBOSS AS** enterprise feature set, we wanted to move to latest **wildfly** but it looks like development on Torquebox side is stopped.

Can it be possible for Torquebox team to share there ideas on how to do this or any pointers.

Thanks in advance and for amazing work you guys did in Torquebox.

**Comment by urenpatelce** [comment]
@bbrowning We are also facing the same issue as @abhichvn so can you please give us some quick pointers on how we can do that? What will be the challenges? We are thinking to Use WildFly 13 directly from ROR application and will try to consume caching, clustering and messaging services directly or will create a middle layer like Torquebox. Can you give your thoughts on this approach or any other ways?

Thanks in advance.
